### ISSUE TITLE
[Bug]: Error initializing backend store

### ISSUE THREAD

**Issue by lnmohankumar** [oracle/oci-mlflow#16]
### oci-mlflow version used

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/oracle/oci-mlflow/releases) of oci-mlflow.

- [X] I have confirmed this bug exists on the main branch of oci-mlflow.

- [X] I agree to follow the [Code of Conduct](https://github.com/oracle/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Oci-mlfow was working with mysql external mlflow.store.db. We are getting below exception with the latest code.

```
2023/07/28 06:59:29 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2023/07/28 06:59:29 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
2023/07/28 06:59:29 ERROR mlflow.cli: Error initializing backend store
2023/07/28 06:59:29 ERROR mlflow.cli: (mysql.connector.errors.DatabaseError) 3750 (HY000): Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
[SQL: ALTER TABLE metrics DROP PRIMARY KEY ]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
Traceback (most recent call last):
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 3750 (HY000): Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/cli.py", line 404, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 278, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 257, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 118, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 134, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 88, in _initialize_tables
    _upgrade_db(engine)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 212, in _upgrade_db
    command.upgrade(config, "heads")
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db_migrations/versions/451aebb31d03_add_metric_step.py", line 26, in upgrade
    batch_op.create_primary_key(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/operations/base.py", line 377, in batch_alter_table
    impl.flush()
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/operations/batch.py", line 113, in flush
    fn(*arg, **kw)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/ddl/mysql.py", line 155, in drop_constraint
    super().drop_constraint(const)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/ddl/impl.py", line 338, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 3750 (HY000): Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
[SQL: ALTER TABLE metrics DROP PRIMARY KEY ]
(Background on this error at: https://sqlalche.me/e/20/4xp6)

``` 

### How to Reproduce

```python
build latest main branch and bring up the tracker server with mssql external store.
```

### What was Observed

ML flow start up error 

### What was Expected

ML server start with out any primary key issue 

### Version

<details>
Paste here the output of ``pip freeze | grep oci-mlflow``
</details>

latest version

**Comment by lnmohankumar** [comment]
re running the mlflow tracker server giver below metrics table erroe and I am unable to move from this.

```python
2023/07/28 07:49:46 ERROR mlflow.cli: Error initializing backend store
2023/07/28 07:49:46 ERROR mlflow.cli: (mysql.connector.errors.ProgrammingError) 1060 (42S21): Duplicate column name 'step'
[SQL: ALTER TABLE metrics ADD COLUMN step BIGINT NOT NULL DEFAULT '0']
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Duplicate column name 'step'

The above exception was the direct cause of the following exception:



Traceback (most recent call last):
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1060 (42S21): Duplicate column name 'step'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/cli.py", line 404, in server
    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 278, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 257, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/server/handlers.py", line 118, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 134, in __init__
    mlflow.store.db.utils._initialize_tables(self.engine)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 88, in _initialize_tables
    _upgrade_db(engine)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db/utils.py", line 212, in _upgrade_db
    command.upgrade(config, "heads")
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db_migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db_migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mlflow/store/db_migrations/versions/451aebb31d03_add_metric_step.py", line 20, in upgrade
    op.add_column("metrics", sa.Column("step", sa.BigInteger(), nullable=False, server_default="0"))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/operations/ops.py", line 2119, in add_column
    return operations.invoke(op)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/operations/base.py", line 395, in invoke
    return fn(self, operation)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 154, in add_column
    operations.impl.add_column(table_name, column, schema=schema, **kw)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/ddl/impl.py", line 322, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "/miniconda/envs/oci-mlflow/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1060 (42S21): Duplicate column name 'step'
[SQL: ALTER TABLE metrics ADD COLUMN step BIGINT NOT NULL DEFAULT '0']
(Background on this error at: https://sqlalche.me/e/20/f405)

``` 
still the query complaints. 

 MySQL  10.0.0.41:3306 ssl  mlflow  SQL > describe metrics;
+-----------+--------------+------+-----+---------+-------+
| Field     | Type         | Null | Key | Default | Extra |
+-----------+--------------+------+-----+---------+-------+
| key       | varchar(250) | NO   | PRI | NULL    |       |
| value     | float        | NO   |     | NULL    |       |
| timestamp | bigint       | NO   | PRI | NULL    |       |
| run_uuid  | varchar(32)  | NO   | PRI | NULL    |       |
| step      | bigint       | NO   |     | 0       |       |
+-----------+--------------+------+-----+---------+-------+

**Comment by lnmohankumar** [comment]
Issue: While creating the msql instance the configuration had the configuration **sql_require_primary_key** set to **ON**
![image](https://github.com/oracle/oci-mlflow/assets/12134539/da6103bc-70c7-4b51-87a1-6091d4cddd3c)

This caused the above exception.

Solution: choose the configuration with out this parameter set and mlflow server comes up. Hence closing this issue.

**Comment by lnmohankumar** [comment]
verified and closed.
